// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCQKNX71VMCNu-d5ku7CLdhFr1P36msp4',
    appId: '1:291063708231:web:046e0b09aa51ee89644f62',
    messagingSenderId: '291063708231',
    projectId: 'habapp-5d4c1',
    authDomain: 'habapp-5d4c1.firebaseapp.com',
    storageBucket: 'habapp-5d4c1.firebasestorage.app',
    measurementId: 'G-02T9VYJYDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLoT9IAA0tKVusJV2yVZK8SkhX4u-3cEc',
    appId: '1:291063708231:android:e350e5c95c103ba1644f62',
    messagingSenderId: '291063708231',
    projectId: 'habapp-5d4c1',
    storageBucket: 'habapp-5d4c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuaiA_vzS19sM0NBug0ZvOmMnhmUUO8kg',
    appId: '1:291063708231:ios:b9d38755faa88666644f62',
    messagingSenderId: '291063708231',
    projectId: 'habapp-5d4c1',
    storageBucket: 'habapp-5d4c1.firebasestorage.app',
    iosBundleId: 'com.hab.codingclub',
  );
}
